# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

os:
    - linux

# Use Travis' container-based architecture
sudo: false

addons:
  apt:
    packages:
    - graphviz
    - texlive-latex-extra
    - dvipng

env:
    global:
        # The following versions are the 'default' for tests, unless
        # overidden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - PYTHON_VERSION=3.6
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=stable
        - CONDA_DEPENDENCIES='semantic_version jsonschema pyyaml six lz4'
        - PIP_DEPENDENCIES_FLAGS='--no-deps --force'
        - PIP_DEPENDENCIES='git+http://github.com/spacetelescope/gwcs.git#egg=gwcs'
        - SETUP_CMD='test --remote-data'

    matrix:
          # Make sure we grab a Py2-compatible version of gwcs
        - PYTHON_VERSION=2.7 SETUP_CMD='test' PIP_DEPENDENCIES='gwcs==0.8'
        - PYTHON_VERSION=3.5 SETUP_CMD='test' ASTROPY_VERSION=development
        - PYTHON_VERSION=3.6 SETUP_CMD='test' ASTROPY_VERSION=development

matrix:
    include:

        # Do a coverage test
        - env: SETUP_CMD='test --coverage --open-files --remote-data'
               ASTROPY_VERSION=development

        # Check for sphinx doc build warnings - we do this first because it
        # may run for a long time
        - env: SETUP_CMD='build_docs -w'

        # try older astropy versions
        - env: PYTHON_VERSION=3.5
               NUMPY_VERSION=1.11 ASTROPY_VERSION=1.2.1 SETUP_CMD='test'
        - env: NUMPY_VERSION=1.12 ASTROPY_VERSION=1.3.3 SETUP_CMD='test'
        - env: ASTROPY_VERSION=2.0.4 SETUP_CMD='test'
        - env: ASTROPY_VERSION=2.0.4 SETUP_CMD='test'
               CONDA_DEPENDENCIES='pytest-astropy semantic_version jsonschema pyyaml six lz4'

        # latest stable versions
        - env: NUMPY_VERSION=stable ASTROPY_VERSION=stable SETUP_CMD='test'
               CONDA_DEPENDENCIES='pytest-astropy semantic_version jsonschema pyyaml six lz4'

        # Try a run on OSX
        - os: osx
          env: NUMPY_VERSION=stable ASTROPY_VERSION=stable SETUP_CMD='test'
               CONDA_DEPENDENCIES='pytest-astropy semantic_version jsonschema pyyaml six lz4'

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh

script:
   - python setup.py $SETUP_CMD

after_success:
    # If coveralls.io is set up for this package, uncomment the line
    # below and replace "packagename" with the name of your package.
    # The coveragerc file may be customized as needed for your package.
    - if [[ $SETUP_CMD == 'test --coverage --open-files --remote-data' ]]; then coveralls --rcfile='asdf/tests/coveragerc'; fi
