# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

os:
    - linux

# Use Travis' container-based architecture
sudo: false

addons:
  apt:
    packages:
    - graphviz
    - texlive-latex-extra
    - dvipng

env:
    global:
        # The following versions are the 'default' for tests, unless
        # overidden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - PYTHON_VERSION=3.6
        - PYTEST_VERSION=3.10
        - ASTROPY_VERSION=stable
        - NUMPY_VERSION=stable
        - ALL_PIP_DEPENDENCIES='pytest-faulthandler importlib_resources'
        - PIP_DEPENDENCIES="$ALL_PIP_DEPENDENCIES"
        - ALL_CONDA_DEPENDENCIES='semantic_version jsonschema pyyaml six lz4 pytest-astropy'
        - CONDA_DEPENDENCIES="$ALL_CONDA_DEPENDENCIES"
        - GWCS_GIT='git+git://github.com/spacetelescope/gwcs.git#egg=gwcs'
        - GWCS_PIP='gwcs'
        - RUN_CMD='pytest'

    matrix:
        # Make sure that installation does not fail
        - RUN_CMD='python setup.py install'
        # Make sure README will display properly on pypi
        - PIP_DEPENDENCIES='twine' TWINE_CHECK=1
        - PYTHON_VERSION=3.5
        - PYTHON_VERSION=3.6 PYTEST_VERSION=3.8
        - PYTHON_VERSION=3.7 PYTEST_VERSION=3.9

matrix:
    fast_finish: true
    include:

        # Do a coverage test
        - env: COVERAGE=1
               PIP_DEPENDENCIES="$ALL_PIP_DEPENDENCIES coverage coveralls"

        # Check for sphinx doc build warnings - we do this first because it
        # may run for a long time
        - env: RUN_CMD='python setup.py build_docs -w'
               CONDA_DEPENDENCIES="$ALL_CONDA_DEPENDENCIES sphinx-astropy"

        # Do a code style check
        - env: RUN_CMD="flake8 asdf --count"
               PIP_DEPENDENCIES="$ALL_PIP_DEPENDENCIES flake8"

        # try older numpy versions
        - env: PYTHON_VERSION=3.5 NUMPY_VERSION=1.11
        - env: NUMPY_VERSION=1.12

        # also test against development version of Astropy
        - env: ASTROPY_VERSION=development GWCS_PIP="$GWCS_GIT"

        # latest stable versions
        - env: NUMPY_VERSION=stable

        # Test against development version of numpy (this job can fail)
        - env: NUMPY_VERSION=development

        # Try a run on OSX
        - os: osx
          env: NUMPY_VERSION=stable

        # Test against latest version of jsonschema
        - env: PIP_DEPENDENCIES='jsonschema pytest-faulthandler importlib_resources'

    allow_failures:
        - env: NUMPY_VERSION=development
        - env: PIP_DEPENDENCIES='jsonschema pytest-faulthandler importlib_resources'

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh
    - python -m pip install --no-deps $GWCS_PIP
    - python setup.py install

script:
    - if [[ $TWINE_CHECK ]]; then
        python setup.py build sdist;
        twine check dist/*;
      elif [[ $COVERAGE ]]; then
        coverage run --source=asdf -m pytest --remote-data --open-files;
        coverage report -m;
      else
        $RUN_CMD;
      fi

after_success:
    # If coveralls.io is set up for this package, uncomment the line
    # below and replace "packagename" with the name of your package.
    # The coveragerc file may be customized as needed for your package.
    - if [[ $COVERAGE ]]; then coveralls --rcfile='asdf/tests/coveragerc'; fi
