# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

os:
    - linux

# Use Travis' container-based architecture
sudo: false

addons:
  apt:
    packages:
    - graphviz
    - texlive-latex-extra
    - dvipng

env:
    global:
        # The following versions are the 'default' for tests, unless
        # overidden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - TOX_CMD='tox --'
        - TOX_ARGS='--remote-data'

    matrix:
        # Make sure that installation does not fail
        - TOXENV='py36-stable' TOX_CMD='tox --notest' TOX_ARGS=''
        # Make sure README will display properly on pypi
        - TOXENV='checkdocs'
        - TOXENV='py35-stable'
        - TOXENV='py36-stable'
        - TOXENV='py37-stable'

matrix:
    fast_finish: true
    include:

        # Do a coverage test
        - env: TOXENV='coverage' TOX_ARGS=''

        # Check for sphinx doc build warnings - we do this first because it
        # may run for a long time
        - env: TOXENV='docbuild' TOX_ARGS=''

        # Do a code style check
        - env: TOXENV='style' TOX_ARGS=''

        # try older numpy versions
        - env: TOXENV='py35-numpy11'
        - env: TOXENV='py36-numpy12'

        # also test against development versions of Astropy and GWCS
        - env: TOXENV='py36-astropydev-gwcsdev'

        # Test against development version of numpy (this job can fail)
        - env: TOXENV='py37-numpydev'

        # Try a run on OSX
        - os: osx
          env: TOXENV='py37-stable'

        - os: windows
          env: TOXENV='py37-stable' TOX_ARGS='--remote-data'

        - os: windows
          env: TOXENV='py35-stable'

        - os: windows
          env: TOXENV='py36-stable'

        # Windows test against development version of numpy (this job can fail)
        - os: windows
          env: TOXENV='py37-numpydev'


    allow_failures:
        - env: TOXENV='py37-numpydev'

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh
    - pip install tox tox-conda

script:
   - $TOX_CMD $TOX_ARGS

after_success:
    # If coveralls.io is set up for this package, uncomment the line
    # below and replace "packagename" with the name of your package.
    # The coveragerc file may be customized as needed for your package.
    - if [[ $TOXENV == 'coverage' ]]; then coveralls --rcfile='asdf/tests/coveragerc'; fi
